name: publish container images
on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - uses: docker/setup-buildx-action@v1

      - name: Login in to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Dynamic Console container image
        run: ./build.sh
        env:
          SUPPORT_MULTI_ARCH: "true"
          CONSOLE_PLUGIN_IMAGE_REPO: 'ghcr.io/${{ github.repository }}'
          CONSOLE_PLUGIN_IMAGE_TAG: '${{ github.ref_name }}'
